# Generated by Django 5.0.14 on 2025-08-26 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(default="4CH Controller", max_length=128)),
                ("desired_ch1", models.BooleanField(default=False)),
                ("desired_ch2", models.BooleanField(default=False)),
                ("desired_ch3", models.BooleanField(default=False)),
                ("desired_ch4", models.BooleanField(default=False)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DeviceReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ch1", models.BooleanField(default=False)),
                ("ch2", models.BooleanField(default=False)),
                ("ch3", models.BooleanField(default=False)),
                ("ch4", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="automation.device",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
